#1 Update README.md v0.0.5-alpha
WepinWallet/wepin-widget-js-sdk pull request #2
Opened 2023-02-03 09:55 UTC by jwp9533

2023-02-03 09:57 UTC, KyungeunKim requested changes

2023-02-03 09:57 UTC, KyungeunKim commented on README.md
> +	type: 'floating',
아직 floating 지원 안하니깐.. show를 기본으로 해주세요.

2023-02-03 09:57 UTC, KyungeunKim commented on README.md
> +    - `'eth'`: Ethereum
아직 지원하지 않는 btc, eth는 제거해주세요.

2023-02-06 01:13 UTC, jwp9533 commented on README.md
> +	type: 'floating',
floating 관련 내용 제거하고, 예시에서 show로 변경했습니다.

2023-02-06 01:14 UTC, jwp9533 commented on README.md
> +    - `'eth'`: Ethereum
btc, eth 제거했습니다.

2023-02-08 06:31 UTC, KyungeunKim approved these changes

2023-02-20 05:15 UTC, merged